### ISSUE TITLE
Incompatible with latest KIM API v2.0 changes

### ISSUE THREAD

**Issue by dschopf** [mjwen/Three_Body_Stillinger_Weber__MD_335816936951_003#1]
Hi Mingjian,

after the latest updates from Ryan the model driver no longer compiles because of the missing `description` parameter to SetParameterPointer. Could you fix this?

Also the CMakeLists.txt file needs a minor update on my machine to be able to properly compile the driver (I just copied the changed lines from any example model driver):
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8e2885d..8a8d6ec 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,8 +39,8 @@
 
 cmake_minimum_required(VERSION 3.4)
 
-list(APPEND CMAKE_MODULE_PATH $ENV{KIM_API_V2_CMAKE_MODULES_DIR})
-find_package(KIM-API-V2 2.0 REQUIRED)
+list(APPEND CMAKE_PREFIX_PATH $ENV{KIM_API_V2_CMAKE_PREFIX_DIR})
+find_package(KIM-API-V2 2.0 REQUIRED CONFIG)
 if(NOT TARGET kim-api)
   project("${KIM_API_PROJECT_NAME}" VERSION "${KIM_API_VERSION}"
     LANGUAGES CXX C Fortran)
```

**Comment by mjwen** [comment]
@dschopf Thanks for the remainder. I've updated the driver to be compatible with the latest api. Also updated the CMakeLists.txt of the driver and models.
